const BOOKS_AUTOCOMPLETE_SUCCESS = 'BOOKS_AUTOCOMPLETE_SUCCESS';
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
const CLEAR_AUTOCOMPLETE = 'CLEAR_AUTOCOMPLETE';

export { BOOKS_AUTOCOMPLETE_SUCCESS, FETCH_BOOKS_SUCCESS, CLEAR_AUTOCOMPLETE };
